import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { client, db } from "./index";
import { projects } from "./schema";
import { eq } from "drizzle-orm";
import crypto from "crypto";

const initialProjects = [
  {
    slug: "uzee-tech",
    title: "UZEE TECH",
    category: "Branding & Web Development",
    shortDescription: "Premium digital identity and custom website development for a next-gen technology provider.",
    description: "BrandHive Studio created a cohesive and modern corporate brand system for UZEE TECH. We designed their brand identity mark, corporate stationery, promotional material, social media kits, and engineered a custom, high-speed corporate web platform to align with their forward-looking technology services.",
    coverImage: "/images/portfolio/covers/portfolio-uzee-tech-cover.png",
    logoImage: "/images/portfolio/UZEE%20TECH/01%20Logo/logo-icon.png",
    client: "Umar Farook",
    role: "Founder",
    year: "2026",
    deliverables: JSON.stringify(["Brand Strategy", "Logo Design", "Stationery Design", "Social Media Kit", "Web Development"]),
    isFeatured: true,
    isOngoing: false,
    isPublished: true,
    displayOrder: 1,
  },
  {
    slug: "qdx-express",
    title: "QDX Express",
    category: "Brand Identity & Logistics Design",
    shortDescription: "A complete branding system and visual strategy for a modern logistics company.",
    description: "For QDX Express, we crafted a high-energy brand identity reflecting speed, reliability, and precision. We created marketing assets, brand guidelines, vehicle wrap design layouts, and digital strategy packages to elevate their logistical operations.",
    coverImage: "/images/portfolio/covers/portfolio-qdx-express-cover.png",
    logoImage: "/images/portfolio/QDX%20Express/01%20Logo%20Design/Primary%20Logo.png",
    client: "QDX Logistics Ltd",
    role: "Corporate Client",
    year: "2025",
    deliverables: JSON.stringify(["Brand Identity", "Vehicle Design", "Digital Strategy"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 2,
  },
  {
    slug: "ruhunu-spice-food",
    title: "Ruhunu Spice & Food",
    category: "Packaging & Brand Identity",
    shortDescription: "Authentic packaging designs and traditional brand identity for a premium spice manufacturer.",
    description: "We designed heritage-inspired packaging and a warm corporate identity for Ruhunu Spice & Food. We crafted label designs, traditional spice packets, business cards, menu cards, and corporate presentation packages highlighting premium natural quality.",
    coverImage: "/images/portfolio/covers/portfolio-ruhunu-spice-cover.png",
    logoImage: "/images/portfolio/Ruhunu%20Spice%20%26%20Food/01%20Logo%20Design/Ruhunu_Spice_Food_Logo.png",
    client: "Ruhunu Spice Exports",
    role: "Director of Brand",
    year: "2026",
    deliverables: JSON.stringify(["Label Design", "Packaging Layouts", "Logo Identity", "Stationery Design"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 3,
  },
  {
    slug: "mobicare",
    title: "Mobicare",
    category: "Branding & UI/UX Design",
    shortDescription: "Mobile repair service branding, social media assets, and UI/UX design concepts.",
    description: "We established a high-trust digital footprint for Mobicare. Our package included brand identity guidelines, marketing material, social media grids, and a modern website user interface concept that streamlines device repair booking.",
    coverImage: "/images/portfolio/covers/portfolio-mobicare-cover.png",
    logoImage: "/images/portfolio/Mobicare/01%20Logo%20Design/MOBICARE_Brand_Icon.png",
    client: "Mobicare Sri Lanka",
    role: "Operations Manager",
    year: "2025",
    deliverables: JSON.stringify(["Logo Design", "Social Media Layouts", "UI/UX Design", "Website Concept"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 4,
  },
  {
    slug: "seya-beauty-studio",
    title: "Seya Beauty Studio",
    category: "Luxury Branding & UI/UX",
    shortDescription: "A high-end salon branding system, social media identity, and booking experience design.",
    description: "Seya Beauty Studio requested an elegant, clean, and premium identity system. We styled their typography palette, curated a clean pastel color theme, designed marketing assets, and configured a booking user experience layout that fits high-end luxury styling.",
    coverImage: "/images/portfolio/covers/portfolio-seya-beauty-cover.png",
    logoImage: "/images/portfolio/Seya%20Beauty%20Studio/01%20Logo%20Design/Seya_Beauty_Studio_Logo_Light.png",
    client: "Tharindi Jayasuriya",
    role: "Founder",
    year: "2026",
    deliverables: JSON.stringify(["Brand Identity", "Luxury Logo", "Stationery Design", "Booking UI Concept"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 5,
  },
  {
    slug: "leo-villas",
    title: "Leo Villas",
    category: "Real Estate Branding & Identity",
    shortDescription: "Premium branding, print stationery, and property presentation materials for luxury villas.",
    description: "For Leo Villas, we developed a premium hospitality brand system. This covers real estate portfolio layouts, letterheads, business cards, estate brochures, and high-fidelity social presentation blocks created to attract high-end property investors.",
    coverImage: "/images/portfolio/covers/portfolio-leo-villas-cover.png",
    logoImage: "/images/portfolio/Leo%20Villas/01%20Logo%20Design/Leo_Villas_Official_Logo.png",
    client: "Ajay Kumar",
    role: "Owner",
    year: "2026",
    deliverables: JSON.stringify(["Real Estate Branding", "Print Stationery", "Brochure Layouts", "Social Kits"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 6,
  },
  {
    slug: "vista-travels-and-tours",
    title: "Vista Travels and Tours",
    category: "Travel Booking & Experience",
    shortDescription: "Full-stack travel booking website offering comprehensive tour packages and booking management.",
    description: "A full-stack travel booking website designed to manage tours, package details, and customer reservations with a polished, customer-friendly interface.",
    coverImage: "/images/portfolio/Vista%20Travels%20and%20Tours/02%20Website/home.png",
    logoImage: "/images/portfolio/Vista%20Travels%20and%20Tours/01%20Logo/logo.png",
    client: "Vista Travels",
    role: "Platform Owner",
    year: "2026",
    deliverables: JSON.stringify(["Travel Booking", "Package Management", "Node.js Full-Stack"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 7,
  },
  {
    slug: "bethel-ceylon-tours",
    title: "Bethel Ceylon Tours",
    category: "Travel Management & Customer Experience",
    shortDescription: "Travel management website designed to streamline tour operations and customer inquiries.",
    description: "A customer-focused travel management site built to simplify tour bookings, inquiry handling, and operator workflows for boutique travel services.",
    coverImage: "/images/portfolio/Bethel%20Ceylon%20Tours/02%20Website/Home.png",
    logoImage: "/images/portfolio/Bethel%20Ceylon%20Tours/01%20Logo/logo.png",
    client: "Bethel Ceylon Tours",
    role: "Travel Operations",
    year: "2026",
    deliverables: JSON.stringify(["Tour Management", "Inquiry Workflows", "Web Experience"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 8,
  },
  {
    slug: "hardware-store",
    title: "Hardware Store",
    category: "E-commerce Platform",
    shortDescription: "Modern e-commerce platform for hardware supplies with dynamic product catalog.",
    description: "A modern hardware e-commerce experience featuring a dynamic product catalog, inventory browsing, and smooth checkout flow.",
    coverImage: "/images/portfolio/Hardware%20Store/02%20Website/login.png",
    logoImage: "/images/portfolio/Hardware%20Store/01%20Logo/logo.png",
    client: "Hardware Store",
    role: "Store Owner",
    year: "2026",
    deliverables: JSON.stringify(["E-commerce", "Product Catalog", "Checkout Flow"]),
    isFeatured: false,
    isOngoing: false,
    isPublished: true,
    displayOrder: 9,
  },
  {
    slug: "hotel-management-system",
    title: "Hotel Management System",
    category: "Hospitality & Booking System",
    shortDescription: "Web-based platform for managing hotel reservations, rooms, and guest services efficiently.",
    description: "A hospitality management system built to streamline room reservations, guest check-in workflows, and service requests for hotel teams.",
    coverImage: "/images/portfolio/hero/portfolio-premium-showcase.webp",
    logoImage: "/images/portfolio/hero/floating-glass-portfolio-cards.webp",
    client: "Hotel Management",
    role: "Operations Manager",
    year: "2026",
    deliverables: JSON.stringify(["Reservation System", "Guest Dashboard", "Room Management"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 10,
  },
  {
    slug: "hr-automation-system",
    title: "HR Automation System",
    category: "Desktop HR Automation",
    shortDescription: "Desktop application for automating HR workflows, employee records, and administrative tasks.",
    description: "A desktop HR automation tool designed to simplify employee onboarding, recordkeeping, and administrative approvals.",
    coverImage: "/images/portfolio/hero/portfolio-multi-device-presentation.webp",
    logoImage: "/images/portfolio/hero/portfolio-premium-showcase.webp",
    client: "HR Automation",
    role: "HR Director",
    year: "2026",
    deliverables: JSON.stringify(["Workflow Automation", "Employee Records", "Desktop App"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 11,
  },
  {
    slug: "thanking-notes-app",
    title: "Thanking Notes App",
    category: "Employee Communication",
    shortDescription: "Internal communication desktop system for employees to share appreciation and notes.",
    description: "We built a desktop-first recognition platform for teams with a warm visual system, quick note creation flows, and integrated appreciation feeds.",
    coverImage: "/images/portfolio/covers/portfolio-thanking-notes-app-cover.svg",
    logoImage: "/images/portfolio/logos/portfolio-thanking-notes-app-logo.svg",
    client: "Thanking Notes",
    role: "Team Lead",
    year: "2026",
    deliverables: JSON.stringify(["Desktop UX", "Recognition System", "Team Communication", "Iconography"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 12,
  },
  {
    slug: "caravan-fresh-cafeteria",
    title: "Caravan Fresh Cafeteria",
    category: "Cafeteria Management Dashboard",
    shortDescription: "Comprehensive cafeteria management system with order processing, menu management, and authentication.",
    description: "We designed a clean dashboard for cafeteria managers to handle daily menus, orders, inventory, and staff authentication with clarity and speed.",
    coverImage: "/images/portfolio/covers/portfolio-caravan-fresh-cafeteria-cover.svg",
    logoImage: "/images/portfolio/logos/portfolio-caravan-fresh-cafeteria-logo.svg",
    client: "Caravan Fresh Cafeteria",
    role: "Operations Lead",
    year: "2026",
    deliverables: JSON.stringify(["Dashboard UI", "Order Management", "Menu Design", "Authentication"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 13,
  },
  {
    slug: "payment-management-system",
    title: "Payment Management System",
    category: "Secure Transaction Platform",
    shortDescription: "Secure transaction management system built with strong Object-Oriented Programming principles.",
    description: "We crafted a secure payment dashboard with transaction control, reconciliation screens, and audit-friendly reporting for finance teams.",
    coverImage: "/images/portfolio/covers/portfolio-payment-management-system-cover.svg",
    logoImage: "/images/portfolio/logos/portfolio-payment-management-system-logo.svg",
    client: "Payment Management",
    role: "Product Owner",
    year: "2026",
    deliverables: JSON.stringify(["Secure UI", "Transaction Workflows", "Audit Reporting", "OOP Architecture"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 14,
  },
  {
    slug: "mathi-quiz-game",
    title: "Mathi Quiz Game",
    category: "Mobile Quiz & Gamification",
    shortDescription: "Engaging mobile quiz application featuring timed challenges and dynamic scoring systems.",
    description: "We created a playful mobile quiz experience with timed challenges, animated scoring, and a supportive learning progression system.",
    coverImage: "/images/portfolio/covers/portfolio-mathi-quiz-game-cover.svg",
    logoImage: "/images/portfolio/logos/portfolio-mathi-quiz-game-logo.svg",
    client: "Mathi Games",
    role: "App Designer",
    year: "2026",
    deliverables: JSON.stringify(["Game UI", "Mobile Interface", "Gamification", "Scoring System"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 15,
  },
  {
    slug: "blossom-task",
    title: "Blossom Task",
    category: "Task Management & Productivity",
    shortDescription: "Task management application supporting full CRUD operations and deadline tracking.",
    description: "A productivity app built to manage tasks, deadlines, and team collaboration with clear status and deadline tracking.",
    coverImage: "/images/portfolio/hero/portfolio-premium-showcase.webp",
    logoImage: "/images/portfolio/hero/portfolio-multi-device-presentation.webp",
    client: "Blossom Task",
    role: "Product Manager",
    year: "2026",
    deliverables: JSON.stringify(["Task Tracking", "CRUD Workflow", "Deadline Management"]),
    isFeatured: false,
    isOngoing: true,
    isPublished: true,
    displayOrder: 16,
  },
];

async function seedProjects() {
  console.log("🌱 Seeding portfolio projects into Turso...");

  let createdCount = 0;
  let skippedCount = 0;

  for (const item of initialProjects) {
    const existing = await db
      .select({ id: projects.id })
      .from(projects)
      .where(eq(projects.slug, item.slug))
      .limit(1);

    if (existing.length > 0) {
      skippedCount++;
      continue;
    }

    await db.insert(projects).values({
      id: "proj_" + crypto.randomUUID(),
      slug: item.slug,
      title: item.title,
      category: item.category,
      shortDescription: item.shortDescription,
      description: item.description,
      coverImage: item.coverImage,
      logoImage: item.logoImage,
      client: item.client,
      role: item.role,
      year: item.year,
      deliverables: item.deliverables,
      isFeatured: item.isFeatured,
      isOngoing: item.isOngoing,
      isPublished: item.isPublished,
      displayOrder: item.displayOrder,
    });

    createdCount++;
    console.log(`  ✓ Created project: ${item.title} (${item.slug})`);
  }

  console.log(`\n✅ Projects seed completed: ${createdCount} created, ${skippedCount} already existed.`);
}

seedProjects()
  .catch((err) => {
    console.error("Seed projects failed:", err);
    process.exit(1);
  })
  .finally(() => {
    client.close();
  });
